language: node_js

env:
  - CXX=g++-4.8

node_js:
  - "6"

addons:
  apt:
    packages:
    - g++-4.8

sudo: false

before_install:
  - $CXX --version
  - if [ "$TRAVIS_NODE_VERSION" = "0.8" ]; then npm install -g npm@2.7.3; fi;

install: true